[package]
name = "smartproof"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[[bin]]
name = "smartproof"
path = "src/main.rs"

[dependencies]
clap = { version = "4.1.1", features = ["cargo"] }
clap-verbosity-flag = "2.0.1"
